name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Clojure cache
        uses: actions/cache@v3
        id: clojure-cache
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            key: ${{ runner.os }}-clojure-${{ hashFiles('**/deps.edn', 'bb.edn') }}
            restore-keys: |
            ${{ runner.os }}-clojure-

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
  
      - name: Set up Clojure and Babashka
        uses: DeLaGuardo/setup-clojure@12.2
        with:
          # https://clojure.org/releases/tools
          cli: '1.11.1.1435'
          # https://github.com/babashka/babashka/releases
          bb: '1.3.186'

      - run: bb compile
      - run: bb check
      - run: bb test
      - run: bb jar

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-build
          path: |
            target/*.jar
            target/coverage/

      - name: Deploy Jars
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: bb deploy
        env:
          CLOJARS_USERNAME: scarlet
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_DEPLOY_TOKEN }}
